server:
  port: 8888
spring:
  application:
    name:
      microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka/
  instance:
    metadata-map:
      my-metadata:
        我自己定义的元数据
## INFO
info: 
  app: 
    name: microservice-simple-provider-user-my-metadata
    encoding: UTF-8
    java:
      source: 1.8.0_201
      target: 1.8.0_201
management:
  security:
    enabled: false


