server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
  rabbitmq:
    host: 47.106.193.40
    port: 5672
    password: guest
    username: guest
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
