server:
    port: 8181
spring:
    datasource:
        druid:
            url: jdbc:mysql://47.106.193.40:3306/yyw?useUnicode=true&characterEncoding=UTF8&&serverTimezone=UTC&useSSL=false
            username: root
            password: 123456
            min-idle: 5
            max-active: 150
            max-wait: 60000
            pool-prepared-statements: false
            max-open-prepared-statements: 0
            validation-query: select 'x'
            test-while-idle: true
            test-on-borrow: true
            test-on-return: false
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
mybatis:
    mapper-locations: classpath:mybatis/*.xml
logging:
    level:
        com.yyw.mapper: DEBUG

